### ISSUE TITLE
An error occurred while querying your MongoDB deployment. Please try again in a few minutes.

### ISSUE THREAD

**Issue by MaurerKrisztian** [MaurerKrisztian/TaskManager-api#2]
https://www.mongodb.com/community/forums/t/an-unexpected-error-occurred-please-try-again-later/101262/5

**Comment by MaurerKrisztian** [comment]
`[Nest] 1  - 04/20/2022, 4:23:13 PM   ERROR [MongooseModule] Unable to connect to the database. Retrying (1)...
[Nest] 1  - 04/20/2022, 4:23:13 PM   ERROR [ExceptionHandler] Server selection timed out after 30000 ms
MongooseServerSelectionError: Server selection timed out after 30000 ms
    at NativeConnection.Connection.openUri (/opt/app/node_modules/mongoose/lib/connection.js:801:32)
    at /opt/app/node_modules/mongoose/lib/index.js:341:10
    at /opt/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/opt/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/opt/app/node_modules/mongoose/lib/index.js:1167:10)
    at Mongoose.connect (/opt/app/node_modules/mongoose/lib/index.js:340:20)
    at InstanceWrapper.useFactory [as metatype] (/opt/app/dist/database/database.providers.js:8:36)
    at Injector.instantiateClass (/opt/app/node_modules/@nestjs/core/injector/injector.js:304:55)
    at callback (/opt/app/node_modules/@nestjs/core/injector/injector.js:48:41)`
